export const defaultStyles = [
  {
    selector: 'node',
    style: {
      'background-color': '#666',
      label: 'data(label)',
      width: 60,
      height: 60,
      'font-size': 12,
      'text-valign': 'bottom',
      'text-halign': 'center',
      'text-wrap': 'wrap',
      'text-max-width': 100,
      'background-image': 'data(image)',
      'background-fit': 'cover',
      'background-width': '100%',
      'background-height': '100%',
      'border-width': 3,
      'border-color': '#666',
      'border-opacity': 0.5,
      color: '#ffffff',
      'text-outline-color': '#fff',
      'text-outline-width': 0,
      'text-outline-opacity': 0.5,
      'text-margin-y': 5,
    },
  },
  {
    selector: 'node.highlight-venture-affiliated',
    style: {
      'border-width': '3px',
      'border-color': '#00FFFF',
      'border-style': 'solid',
      'border-opacity': 1,
    },
  },
  {
    selector: 'edge',
    style: {
      width: 2,
      'line-color': '#444',
      'curve-style': 'straight',
      'font-size': 10,
      'text-rotation': 'autorotate',
      'text-margin-y': -10,
      'text-outline-color': '#fff',
      'text-outline-width': 2,
      'text-outline-opacity': 0.5,
    },
  },
  {
    selector: 'edge.highlighted',
    style: {
      'line-color': '#ff0000',
      width: 3,
    },
  },
  {
    selector: 'node.highlighted-node',
    style: {
      'background-color': '#ff0000',
      'border-color': '#ff0000',
      'border-width': 3,
      'border-opacity': 1,
    },
  },
];
